trunk/grails-app/domain/controlegastos/Categoria.groovy
package controlegastos

class Categoria {

	String nome

	String toString() {
		return nome
	}
}

trunk/grails-app/domain/controlegastos/GastoPessoal.groovy
package controlegastos

class GastoPessoal {

    String usuario
    Categoria categoria
    Double valor
    Date dataPagamento
    
    static constraints = {
    	valor(min: 0.01d)
    }
}

trunk/grails-app/domain/controlegastos/Usuario.groovy
package controlegastos

class Usuario {
  static constraints = {
    nomeUsuario(unique:true)
    senha(password:true)
    nome()
    perfil(inList:["Administrador", "Usuario"])
  }



  String nomeUsuario
  String senha
  String nome
  String perfil = "Usuario"

  String toString() {
    nome
  }
}

trunk/grails-app/controllers/controlegastos/BaseController.groovy
package controlegastos

class BaseController {

	def beforeInterceptor = [action:this.&login]


	def login = {
	    if(session.usuario)
	      render (view: '/index')
	    else
	      render (view: '/usuario/login')
	}
}	

trunk/grails-app/controllers/controlegastos/CategoriaController.groovy
package controlegastos

class CategoriaController {

    def scaffold = Categoria
}

trunk/grails-app/controllers/controlegastos/GastoPessoalController.groovy
package controlegastos

class GastoPessoalController {

	def scaffold = GastoPessoal

	def gastosPorCategoria = { render (view: '/gastoPessoal/gastosPorCategoria') }
	
	def crescimentoGastos = { render (view: '/gastoPessoal/crescimentoGastos') }
	
	def renda = {}
		
	def relatorio = {}
}

trunk/grails-app/controllers/controlegastos/UsuarioController.groovy
package controlegastos

class UsuarioController{
  
  def scaffold = Usuario

  def login = {}

  def autenticar = {
    def usuario = Usuario.findByNomeUsuarioAndSenha(params.nomeUsuario, params.senha)
    if(usuario){
      session.usuario = usuario
      redirect(controller:"GastoPessoal", action:"list")
    }else{
      flash.message = "Nao foi possivel autenticar o usuario. Informe os dados corretamente!"
      redirect(action:"login")
    }
  }

  def logout = {
    session.usuario = null
    redirect(controller:"Usuario", action:"login")
  }
}

trunk/grails-app/views/gastoPessoal/_form.gsp
<%@ page import="controlegastos.GastoPessoal" %>



<div class="fieldcontain ${hasErrors(bean: gastoPessoalInstance, field: 'valor', 'error')} required">
	<label for="valor">
		<g:message code="gastoPessoal.valor.label" default="Valor" />
		<span class="required-indicator">*</span>
	</label>
	<g:field type="number" name="valor" min="0.01" required="" value="${fieldValue(bean: gastoPessoalInstance, field: 'valor')}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: gastoPessoalInstance, field: 'categoria', 'error')} required">
	<label for="categoria">
		<g:message code="gastoPessoal.categoria.label" default="Categoria" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="categoria" name="categoria.id" from="${controlegastos.Categoria.list()}" optionKey="id" required="" value="${gastoPessoalInstance?.categoria?.id}" class="many-to-one"/>
</div>

<div class="fieldcontain ${hasErrors(bean: gastoPessoalInstance, field: 'dataPagamento', 'error')} required">
	<label for="dataPagamento">
		<g:message code="gastoPessoal.dataPagamento.label" default="Data Pagamento" />
		<span class="required-indicator">*</span>
	</label>
	<g:datePicker name="dataPagamento" precision="day"  value="${gastoPessoalInstance?.dataPagamento}"  />
</div>

<div class="fieldcontain ${hasErrors(bean: gastoPessoalInstance, field: 'usuario', 'error')} ">
	
	<g:textField style="visibility:hidden;" name="usuario" value="${session.usuario.nome}" />
</div>

trunk/grails-app/views/gastoPessoal/create.gsp
<%@ page import="controlegastos.GastoPessoal" %>
<!doctype html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'gastoPessoal.label', default: 'GastoPessoal')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-gastoPessoal" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="list"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-gastoPessoal" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${gastoPessoalInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${gastoPessoalInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form action="save" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

trunk/grails-app/views/gastoPessoal/crescimentoGastos.gsp
<%@ page import="controlegastos.GastoPessoal"%>
<!doctype html>
<html>
<head>
<meta name="layout" content="main">
<g:set var="entityName"
	value="${message(code: 'gastoPessoal.label', default: 'GastoPessoal')}" />
<title><g:message code="default.create.label"
		args="[entityName]" /></title>
</head>
<body>
	<a href="#create-gastoPessoal" class="skip" tabindex="-1"><g:message
			code="default.link.skip.label" default="Skip to content&hellip;" /></a>
	<div class="nav" role="navigation">
		<ul>
			<li><a class="home" href="${createLink(uri: '/')}"><g:message
						code="default.home.label" /></a></li>
			<li><g:link class="list" action="list">
					<g:message code="default.list.label" args="[entityName]" />
				</g:link></li>
		</ul>
	</div>
	<div id="create-gastoPessoal" class="content scaffold-create"
		role="main">
		<h1></h1>
		<%
		
	def gastos = controlegastos.GastoPessoal.findAll()
		
	def mapaDeGastosPorCategoria = gastos.groupBy {custo -> custo.categoria}
		
	
	def titulos = mapaDeGastosPorCategoria.collect({categoria, gasto -> categoria.nome})
		
	def valores = mapaDeGastosPorCategoria.collect {categoria, gasto -> gasto.valor}
	
	def valoresPlanos = valores.flatten()
		
	def max = valoresPlanos.max()
	def min = valoresPlanos.min()
	def avg = max / 2
	
	def valoresNormalizados = mapaDeGastosPorCategoria.collect {categoria, custos -> custos.collect {((it.valor - min) / max) * 100}}
		
%>

		<g:lineChart title="Crescimento de Gastos Pessoais"
			colors="['8C1F0E', '590031', '376619', '6A8C0E', '1C0459', '1A022E', '030F33', '042B4F', '479D9E', '27738C', '74A0FF', '71B57A', '416131', '637D74', '403D3A', '8C3B3B', 'AB6937', 'AB882D', 'A16169', '942B08', '0C006B', '187843', 'BF5C4C']"
			legend="${titulos}"
			data="${valoresNormalizados}" type="ls" dataType="text" axes="x,y"
			axesLabels="${[0:[], 1:[0, avg, max]]}"
			gridLines="20, 50, 1, 0" />
		<!-- data="${[[1, 2, 3, 50, 70], [70, 50, 3, 2, 1]]}" -->

trunk/grails-app/views/gastoPessoal/edit.gsp
<%@ page import="controlegastos.GastoPessoal" %>
<!doctype html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'gastoPessoal.label', default: 'GastoPessoal')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-gastoPessoal" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="list"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-gastoPessoal" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${gastoPessoalInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${gastoPessoalInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form method="post" >
				<g:hiddenField name="id" value="${gastoPessoalInstance?.id}" />
				<g:hiddenField name="version" value="${gastoPessoalInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" formnovalidate="" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

trunk/grails-app/views/gastoPessoal/gastosPorCategoria.gsp
<%@ page import="controlegastos.GastoPessoal" %>
<!doctype html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'gastoPessoal.label', default: 'GastoPessoal')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-gastoPessoal" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="list"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-gastoPessoal" class="content scaffold-create" role="main">
			<h1></h1>
		<% 
			def gastos = controlegastos.GastoPessoal.findAll()

			def sumario = gastos.groupBy { custo -> custo.categoria }.collect { categoria, custosPorCategoria ->
				[ categoria, custosPorCategoria.sum { it.valor }]
			}

			def titulos = sumario.collect({chave, valor -> chave})
			def dados = sumario.collect({chave, valor -> valor})
		%>

		<g:pieChart title='Gastos por categoria' labels="${titulos}" fill="${'bg,s,efefef'}" dataType='simple' data='${dados}' />	</body>
</html>

trunk/grails-app/views/gastoPessoal/list.gsp
<%@ page import="controlegastos.GastoPessoal" %>
<!doctype html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'gastoPessoal.label', default: 'GastoPessoal')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-gastoPessoal" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
		
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
				<li><g:link class="" action="renda">Compromete Renda</g:link></li>
			</ul>
			
		</div>
		<div id="list-gastoPessoal" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
				<thead>
					<tr>
					
						<g:sortableColumn property="valor" title="${message(code: 'gastoPessoal.valor.label', default: 'Valor')}" />
					
						<th><g:message code="gastoPessoal.categoria.label" default="Categoria" /></th>
					
						<g:sortableColumn property="dataPagamento" title="${message(code: 'gastoPessoal.dataPagamento.label', default: 'Data Pagamento')}" />
					
						<g:sortableColumn property="usuario" title="${message(code: 'gastoPessoal.usuario.label', default: 'Usuario')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${gastoPessoalInstanceList}" status="i" var="gastoPessoalInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${gastoPessoalInstance.id}">${fieldValue(bean: gastoPessoalInstance, field: "valor")}</g:link></td>
					
						<td>${fieldValue(bean: gastoPessoalInstance, field: "categoria")}</td>
					
						<td><g:formatDate format="dd-MM-yyyy" date="${gastoPessoalInstance.dataPagamento}" /></td>
					
						<td>${fieldValue(bean: gastoPessoalInstance, field: "usuario")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>

			<div class="pagination">
				<g:paginate total="${gastoPessoalInstanceTotal}" />
			</div>
			
	
		</div>
	</body>
</html>

trunk/grails-app/views/gastoPessoal/relatorio.gsp

<html>
<head>
<title>Relatorio de Comprometimento de Renda Futura</title>
<style>.fdcabmenu {  font-family: Verdana; font-size: 12px; background-color: #0066CC; font-weight: bold; color: #FFFFFF}</style>
<style>.fdbodymenu {  font-family: Verdana; font-size: 12px; background-color: #99CCFF}</style>
</head>
<body>
			<table>
				<thead>
					<tr class="skip">
						<td colspan="3"><h3>Comprometimento Gastos Futuros</h3></td>
					</tr>

					<tr class="fdcabmenu">
					
						<th><g:message code="gastoPessoal.categoria.label" default="Valor" /></th>
					
						<th><g:message code="gastoPessoal.categoria.label" default="Categoria" /></th>
					
						<th><g:message code="gastoPessoal.categoria.label" default="Data de Pagamento" /></th>
					</tr>
				</thead>
				
				<tbody>
				<%
					def hoje = new Date() - 1
					params["mesReferencia"]
					def results = controlegastos.GastoPessoal.findAll()
					
				%>
				<g:each status="i" in="${results}" var="item">
				    <tr class="${(i % 2) == 0 ? 'fdbodymenu' : 'fdbodymenu'}">
					
						<td><div align="center"><g:link action="show" id="${item.id}">${fieldValue(bean: item, field: "valor")}</g:link></div></td>
					
						<td><div align="center">${fieldValue(bean: item, field: "categoria")}</div></td>
					
						<td><div align="center"><g:formatDate format="dd-MM-yyyy" date="${item.dataPagamento}" /></div></td>
										
					</tr>
  				</g:each>
				</tbody>
			</table>			


</body>
</html>

trunk/grails-app/views/gastoPessoal/renda.gsp
<%@ page import="controlegastos.GastoPessoal" %>
<!doctype html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'gastoPessoal.label', default: 'GastoPessoal')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-gastoPessoal" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="list"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-gastoPessoal" class="content scaffold-create" role="main">
			<h1>Comprometimento de Renda Futura</h1>
			
			<g:form action="relatorio" method="get">
				<fieldset class="form">
					<span id="categoria-label" class="property-label">M&ecirc;s Refer&ecirc;ncia</span>
					<g:textField name="mesReferencia" value="" />
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="visualizar" class="save" value="Visualizar" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

trunk/grails-app/views/gastoPessoal/show.gsp
<%@ page import="controlegastos.GastoPessoal" %>
<!doctype html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'gastoPessoal.label', default: 'GastoPessoal')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-gastoPessoal" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="list"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-gastoPessoal" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list gastoPessoal">
			
				<g:if test="${gastoPessoalInstance?.valor}">
				<li class="fieldcontain">
					<span id="valor-label" class="property-label"><g:message code="gastoPessoal.valor.label" default="Valor" /></span>
					
						<span class="property-value" aria-labelledby="valor-label"><g:fieldValue bean="${gastoPessoalInstance}" field="valor"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${gastoPessoalInstance?.categoria}">
				<li class="fieldcontain">
					<span id="categoria-label" class="property-label"><g:message code="gastoPessoal.categoria.label" default="Categoria" /></span>
					
						<span class="property-value" aria-labelledby="categoria-label"><g:link controller="categoria" action="show" id="${gastoPessoalInstance?.categoria?.id}">${gastoPessoalInstance?.categoria?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
				<g:if test="${gastoPessoalInstance?.dataPagamento}">
				<li class="fieldcontain">
					<span id="dataPagamento-label" class="property-label"><g:message code="gastoPessoal.dataPagamento.label" default="Data Pagamento" /></span>
					
						<span class="property-value" aria-labelledby="dataPagamento-label"><g:formatDate date="${gastoPessoalInstance?.dataPagamento}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${gastoPessoalInstance?.usuario}">
				<li class="fieldcontain">
					<span id="usuario-label" class="property-label"><g:message code="gastoPessoal.usuario.label" default="Usuario" /></span>
					
						<span class="property-value" aria-labelledby="usuario-label"><g:fieldValue bean="${gastoPessoalInstance}" field="usuario"/></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form>
				<fieldset class="buttons">
					<g:hiddenField name="id" value="${gastoPessoalInstance?.id}" />
					<g:link class="edit" action="edit" id="${gastoPessoalInstance?.id}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

trunk/grails-app/views/layouts/main.gsp
<!doctype html>
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"><!--<![endif]-->
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<title><g:layoutTitle default="Grails"/></title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link rel="shortcut icon" href="${resource(dir: 'images', file: 'favicon.ico')}" type="image/x-icon">
		<link rel="apple-touch-icon" href="${resource(dir: 'images', file: 'apple-touch-icon.png')}">
		<link rel="apple-touch-icon" sizes="114x114" href="${resource(dir: 'images', file: 'apple-touch-icon-retina.png')}">
		<link rel="stylesheet" href="${resource(dir: 'css', file: 'main.css')}" type="text/css">
		<link rel="stylesheet" href="${resource(dir: 'css', file: 'mobile.css')}" type="text/css">
		<g:layoutHead/>
        <r:layoutResources />
	
		<style type="text/css" media="screen">
			#status {
				background-color: #eee;
				border: .2em solid #fff;
				margin: 2em 2em 1em;
				padding: 1em;
				width: 12em;
				float: left;
				-moz-box-shadow: 0px 0px 1.25em #ccc;
				-webkit-box-shadow: 0px 0px 1.25em #ccc;
				box-shadow: 0px 0px 1.25em #ccc;
				-moz-border-radius: 0.6em;
				-webkit-border-radius: 0.6em;
				border-radius: 0.6em;
			}

			.ie6 #status {
				display: inline; /* float double margin fix http://www.positioniseverything.net/explorer/doubled-margin.html */
			}

			#status ul {
				font-size: 0.9em;
				list-style-type: none;
				margin-bottom: 0.6em;
				padding: 0;
			}

			#status h1 {
				text-transform: uppercase;
				font-size: 1.1em;
				margin: 0 0 0.3em;
			}

			#page-body {
				margin: 2em 1em 1.25em 18em;
			}

			h1 {
				margin-top: 1em;
				margin-bottom: 0.3em;
				font-size: 2em;
			}

			p {
				margin: 0.25em 0;
			}

			#controller-list ul {
				list-style-position: inside;
			}

			#controller-list li {
				list-style-position: inside;
				margin: 0.25em 0;
			}

			@media screen and (max-width: 480px) {
				#status {
					display: none;
				}

				#page-body {
					margin: 0 1em 1em;
				}

				#page-body h1 {
					margin-top: 0;
				}
			}
		</style>
	
	
	</head>
	<body>
		<div id="grailsLogo" role="banner"><h1>Controle de Gastos Pessoais<h1/></div>
		<g:layoutBody/>
		<div class="footer" role="contentinfo"></div>
		<div id="spinner" class="spinner" style="display:none;"><g:message code="spinner.alt" default="Loading&hellip;"/></div>
		<g:javascript library="application"/>
        <r:layoutResources />
	</body>
</html>

trunk/grails-app/views/usuario/login.gsp
<html>
  <head>
    <meta name="layout" content="main" />
    <title>Autenticacao do Usuario</title>
  </head>
  <body>
    <div class="body">
      <h1>Login</h1>
      <g:if test="${flash.message}">
        <div class="message">${flash.message}</div>
      </g:if>
      <g:form url="[controller:'usuario',action:'autenticar']" method="post" >
        <div class="dialog">
          <table>
            <tbody>
              <tr class="prop">
                <td class="name">
                  <label for="nomeUsuario">Login:</label>
                </td>
                <td>
                  <input type="text" id="nomeUsuario" name="nomeUsuario"/>
                </td>
              </tr>

              <tr class="prop">
                <td class="name">
                  <label for="senha">Senha:</label>
                </td>
                <td>
                  <input type="password" id="senha" name="senha"/>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
        <div class="buttons">
          <span class="button">
            <input class="save" type="submit" value="Entrar" />
          </span>
        </div>
      </g:form>
    </div>
  </body>
</html>